# Generated by Django 3.0.2 on 2020-02-01 21:32
import datetime
from django.db import migrations


def const_init(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    issuing = apps.get_model('person_manager', 'HealthInsuranceCompany')
    db_alias = schema_editor.connection.alias
    issuing.objects.using(db_alias).bulk_create([
        issuing(name="UNDEFINED", pk="-1"),
        issuing(name="Страховая компания АСКО-Центр"),
        issuing(name="ВТБ МС"),
        issuing(name="Ингосстрах-М"),
        issuing(name="Росэнерго"),
        issuing(name="ИНКО-МЕД"),
    ])
    address_type = apps.get_model('person_manager', 'AddressType')
    db_alias = schema_editor.connection.alias
    address_type.objects.using(db_alias).bulk_create([
        address_type(type="REG", name="Адрес регистрации"),
        address_type(type="LOC", name="Адрес местонахождения"),
        address_type(type="POS", name="Адрес почтовый"),
    ])
    card = apps.get_model('person_manager', 'Card')
    db_alias = schema_editor.connection.alias
    card.objects.using(db_alias).bulk_create([
        card(pk="-1", card_number="-1", join_date=datetime.date(1984, 3, 17)),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(const_init),
    ]
