# Generated by Django 3.0.2 on 2020-02-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0003_auto_20200222_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='passport_type',
            field=models.CharField(choices=[('PASSP', 'Паспорт'), ('BIRTH', 'Свидетельство о рождении')], default='PASSP', max_length=5, verbose_name='Тип документа'),
        ),
    ]
