# Generated by Django 3.2.2 on 2021-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0005_auto_20200327_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='locality',
            new_name='settlement',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_string',
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Район'),
        ),
    ]
