# Generated by Django 3.2.5 on 2021-07-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0007_alter_address_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип ДУЛ',
                'verbose_name_plural': 'Тип ДУЛ',
            },
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='SNILS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Номер СНИЛС')),
            ],
            options={
                'verbose_name': 'СНИЛС',
                'verbose_name_plural': 'СНИЛС',
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территория',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='OMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер ОМС')),
                ('insurance_company', models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='person_manager.healthinsurancecompany', verbose_name='Организация, выдавшая ОМС')),
            ],
            options={
                'verbose_name': 'ОМС',
                'verbose_name_plural': 'ОМС',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=5, verbose_name='Серия документа')),
                ('number', models.CharField(max_length=10, verbose_name='Номер документа')),
                ('issuing', models.TextField(blank=True, verbose_name='Кем выдан')),
                ('issue_code', models.CharField(blank=True, max_length=7, verbose_name='Код подразделения')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issue_country', models.CharField(blank=True, default='Российская федерация', max_length=30, verbose_name='Страна')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person_manager.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорт',
                'unique_together': {('series', 'number')},
            },
        ),
    ]
