# Generated by Django 3.2.5 on 2021-07-17 20:07

from django.db import migrations


def init_male(apps, schema_editor):
    initial = apps.get_model('person_manager', 'Male')
    db_alias = schema_editor.connection.alias
    initial.objects.using(db_alias).bulk_create([
        initial(name="Мужской"),
        initial(name="Женский"),
    ])


def init_terrain(apps, schema_editor):
    initial = apps.get_model('person_manager', 'Terrain')
    db_alias = schema_editor.connection.alias
    initial.objects.using(db_alias).bulk_create([
        initial(name="Городская"),
        initial(name="Сельская"),
    ])


def init_dul_type(apps, schema_editor):
    initial = apps.get_model('person_manager', 'DULType')
    db_alias = schema_editor.connection.alias
    initial.objects.using(db_alias).bulk_create([
        initial(name="Паспорт"),
        initial(name="Свидетельство о рождении"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0009_auto_20210717_2305'),
    ]

    operations = [
        migrations.RunPython(init_male),
        migrations.RunPython(init_terrain),
        migrations.RunPython(init_dul_type),
    ]
