# Generated by Django 3.2.5 on 2021-07-17 20:30

from django.db import migrations
from person_manager.models import Person, SNILS


def migrate_snils_data(apps, schema_editor):
    persons = Person.objects.all()
    for person in persons:
        if person.snils_number:
            snils = SNILS()
            snils.number = person.snils_number
            snils.save()
            person.snils = snils
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0010_auto_20210717_2307'),
    ]

    operations = [
        migrations.RunPython(migrate_snils_data),
    ]
