# Generated by Django 3.2.5 on 2021-07-17 20:39

from django.db import migrations
from person_manager.models import Person, Polis


def migrate_oms_data(apps, schema_editor):
    persons = Person.objects.all()
    for person in persons:
        if person.oms_number:
            polis = Polis()
            polis.number = person.oms_number
            polis.insurance_company = person.oms_insurance_company
            polis.save()
            person.oms = polis
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0011_auto_20210717_2330'),
    ]

    operations = [
        migrations.RunPython(migrate_oms_data),
    ]
