# Generated by Django 3.2.5 on 2021-07-17 20:39

from django.db import migrations
from person_manager.models import Person, DULType, DUL


def migrate_dul_data(apps, schema_editor):
    persons = Person.objects.all()
    passport_type = DULType.objects.get(name='Паспорт')
    birthday_type = DULType.objects.get(name='Свидетельство о рождении')
    for person in persons:
        if person.passport_number or person.passport_series:
            dul = DUL()
            if person.passport_type == 'PASSP':
                dul.type = passport_type
            if person.passport_type == 'BIRTH':
                dul.type = birthday_type
            dul.number = person.passport_number
            dul.series = person.passport_series
            dul.issuing = person.passport_issuing
            dul.issue_code = person.passport_issue_code
            dul.issue_date = person.passport_issue_date
            dul.issue_country = person.passport_issue_country
            dul.person = person
            dul.save()


def change_male(apps, schema_editor):
    persons = Person.objects.all()
    for person in persons:
        if person.male == 'М':
            person.male = 'M'
        elif person.male == 'Ж':
            person.male = 'W'
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0012_auto_20210717_2339'),
    ]

    operations = [
        migrations.RunPython(migrate_dul_data),
        migrations.RunPython(change_male),
    ]
