# Generated by Django 3.2.5 on 2021-07-18 15:16

from django.db import migrations, models
import django.db.models.deletion
from person_manager.models import Person, Male, Address, Terrain


def init_male(apps, schema_editor):
    persons = Person.objects.all()
    man = Male.objects.get(name='Мужской')
    woman = Male.objects.get(name='Женский')
    for person in persons:
        if person.male == 'M':
            person.male_fk = man
        else:
            person.male_fk = woman
        person.save()


def init_terrain(apps, schema_editor):
    addresses = Address.objects.all()
    city = Terrain.objects.get(name='Городская')
    terr = Terrain.objects.get(name='Сельская')
    for address in addresses:
        if address.terrain == '1':
            address.terrain_fk = city
        else:
            address.terrain_fk = terr
        address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0013_auto_20210718_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='card',
            new_name='card_fk',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='oms',
            new_name='oms_fk',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='snils',
            new_name='snils_fk',
        ),
        migrations.AddField(
            model_name='address',
            name='terrain_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person_manager.terrain', verbose_name='Местность'),
        ),
        migrations.AddField(
            model_name='person',
            name='male_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person_manager.male', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person_manager.person', verbose_name='Представитель'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='person',
            name='oms_insurance_company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='oms_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_issue_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_issue_country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_issuing',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='snils_number',
        ),
        migrations.RunPython(init_male),
        migrations.RunPython(init_terrain),
    ]
