# Generated by Django 3.2.5 on 2021-07-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0014_auto_20210718_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='terrain',
        ),
        migrations.RemoveField(
            model_name='person',
            name='male',
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='type',
            field=models.CharField(max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dultype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='male',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
    ]
