# Generated by Django 3.2.5 on 2021-07-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0015_auto_20210718_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.ForeignKey(default=1, help_text='Выберите тип адреса: Регистрация/Место пребывания', on_delete=django.db.models.deletion.CASCADE, to='person_manager.addresstype', verbose_name='Тип адреса'),
        ),
        migrations.AlterField(
            model_name='dul',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='dul',
            name='series',
            field=models.CharField(blank=True, max_length=5, verbose_name='Серия документа'),
        ),
        migrations.AlterField(
            model_name='dul',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person_manager.dultype', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person_manager.card', verbose_name='Номер карты'),
        ),
    ]
