# Generated by Django 3.2.5 on 2021-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0017_auto_20210801_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
