# Generated by Django 3.2.5 on 2021-08-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person_manager', '0018_alter_person_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='polis_fk',
        ),
        migrations.RemoveField(
            model_name='smo',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='smo',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='smo',
            name='update_date',
        ),
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dul',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polis',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polis',
            name='person_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_manager.person', verbose_name='Владелец полиса'),
        ),
        migrations.AddField(
            model_name='snils',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='card',
            name='join_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_created',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_updated',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='polis',
            unique_together={('series', 'number')},
        ),
        migrations.AlterModelTable(
            name='smo',
            table='smo',
        ),
    ]
