# Generated by Django 3.2.5 on 2021-08-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0019_auto_20210801_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polis',
            old_name='person_fk',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='polis',
            name='number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Номер полиса'),
        ),
        migrations.AlterField(
            model_name='polis',
            name='polis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person_manager.polistype', verbose_name='Тип полиса'),
        ),
        migrations.AlterField(
            model_name='polis',
            name='series',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Серия полиса'),
        ),
        migrations.AlterField(
            model_name='polis',
            name='smo_id',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='person_manager.smo', verbose_name='Страховая МО'),
        ),
    ]
